mainConfig:
  scenario: "getById"
  type_of_script: "35rps"
  from: "2025-12-09 13:03:39.562"
  to: "2025-12-09 14:16:36.381"

# Конфигурация сервисов скрипта
services:
  # Системные сервисы (НЕ сервисы приложений)
  ssh_service: true          # Скачивание отчетов Gatling по SSH
  grafana_service: true      # Скачивание метрик из Grafana
  gatling_metrics_service: true   # Скачивание метрик Gatling из дашборда
  postgresql_metrics_service: false # Скачивание метрик PostgreSQL из дашборда
  
  # Сервисы приложений (для которых будут скачиваться метрики)
  # Установите true для тех сервисов, для которых нужно скачать метрики
  dh-registry-service: false     # Сервис регистрации
  dh-documents-service: true    # Сервис работы с документами
  dh-files-service: false        # Сервис работы с файлами
  dh-auth-service: false        # Сервис аутентификации (отключен)
  dh-notifications-service: false  # Сервис уведомлений (отключен)
  dh-federal-search-service: false  # Сервис федерального поиска
  dh-objects-info-service: false
  ldm-index-content-controller-service: false
  dh-favorite-service: true
  
  # Gatling скрипты (включить/выключить каждый отдельно)
  gatling_scripts:
    Get_Code_Atributes: false
    Upload_File: false            # Скрипт загрузки файлов
    Create_Document: false
    Federal_Search: false      # Скрипт создания документов
    Attribute_Search_1: false   # Поиск атрибутов v1
    Attribute_Search_2: false    # Поиск атрибутов v2
    Attribute_Search_3: false
    Attribute_Search_4: false
    Get_Documents: false
    Get_Document: true

grafana:
  metrics_config: "metrics_urls.yml"

# Конфигурация для Gatling метрик (вторая Grafana)
gatling_grafana:
  gatling_metrics_config: "gatling_metrics_urls.yml"

postgresql_grafana:
  metrics_config: "metrics_urls.yml"  # Используем общий файл метрик